spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # ⬅️ ОТКЛЮЧИТЕ автоматическое обнаружение всех сервисов
      routes:
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/tasks/**
          filters:
            - name: CircuitBreaker
              args:
                name: taskService
                fallbackUri: forward:/fallback/task-service

server:
  port: 8099

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info,metrics,routes
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    gateway:
      access: read_only
    routes:
      access: read_only

resilience4j:
  circuitbreaker:
    instances:
      taskService:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.boot.actuate: DEBUG
    org.example.gateway: DEBUG