spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Маршрут для аутентификации
        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**
          filters:
            - PrefixPath=/user-service
            - name: CircuitBreaker
              args:
                name: authService
                fallbackUri: forward:/fallback/auth-service

        # Маршрут для пользователей
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/user-service
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/fallback/user-service

        # Маршрут для задач
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/tasks/**
          filters:
            - name: CircuitBreaker
              args:
                name: taskService
                fallbackUri: forward:/fallback/task-service
            - name: Retry
              args:
                retries: 3
                methods: GET,POST
                series: SERVER_ERROR

        # Маршрут для поиска
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/search/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: searchService
                fallbackUri: forward:/fallback/search-service

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
              - "http://localhost:8080"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            exposed-headers:
              - "Authorization"
              - "X-Trace-Id"
            max-age: 3600

      httpclient:
        connect-timeout: 5000
        response-timeout: 10s

server:
  port: 8099

# Специфичные настройки Resilience4j для Gateway
resilience4j:
  circuitbreaker:
    instances:
      authService:
        baseConfig: default
        registerHealthIndicator: true
      userService:
        baseConfig: default
        registerHealthIndicator: true
      taskService:
        baseConfig: default
        registerHealthIndicator: true
      searchService:
        baseConfig: default
        registerHealthIndicator: true
  timelimiter:
    instances:
      authService:
        baseConfig: default
      userService:
        baseConfig: default
      taskService:
        baseConfig: default
      searchService:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info,metrics,routes,circuitbreakers
  endpoint:
    gateway:
      enabled: true
    routes:
      enabled: true
    circuitbreakers:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.circuitbreaker: DEBUG
    reactor.netty: DEBUG
    io.github.resilience4j: DEBUG
  file:
    name: logs/api-gateway.log
    max-size: 10MB
    max-history: 7