spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**
          filters:
            - PrefixPath=/user-service
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/fallback/user-service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/user-service
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/fallback/user-service
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/tasks/**
          filters:
            - name: CircuitBreaker
              args:
                name: taskService
                fallbackUri: forward:/fallback/task-service
                failureRateThreshold: 1      # 1% ошибок = открытие
                minimumNumberOfCalls: 1      # минимум 1 вызов
                slidingWindowSize: 1         # окно 1 вызов
                waitDurationInOpenState: 10s
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/search/(?<segment>.*), /api/search/$\{segment}
            - name: CircuitBreaker
              args:
                name: searchService
                fallbackUri: forward:/fallback/search-service
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            exposed-headers:
              - "Authorization"
            max-age: 3600

server:
  port: 8099

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info,metrics,routes,circuitbreakers,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    gateway:
      access: read_only
    routes:
      access: read_only
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 3s
    instances:
      taskService:
        baseConfig: default
        registerHealthIndicator: true
      userService:
        baseConfig: default
        registerHealthIndicator: true
      searchService:
        baseConfig: default
        registerHealthIndicator: true
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
    instances:
      taskService:
        baseConfig: default
      userService:
        baseConfig: default
      searchService:
        baseConfig: default

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.circuitbreaker: DEBUG
    reactor.netty: DEBUG
    io.github.resilience4j: DEBUG
    org.example.gateway: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %5p [%15.15t] [%X{traceId:-}] %-40.40logger{39} : %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %5p [%15.15t] [%X{traceId:-}] %-40.40logger{39} : %m%n"
  file:
    name: logs/api-gateway.log
    max-size: 10MB
    max-history: 7
    total-size-cap: 100MB