# Общие настройки для всех микросервисов
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud: INFO
    org.example: DEBUG

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false