spring:
  application:
    name: frontend
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

server:
  port: 3000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

app:
  name: Task Management System
  version: 1.0.0
  api:
    gateway:
      url: http://localhost:8099
    task-service:
      url: ${app.api.gateway.url}/api/tasks
    user-service:
      url: ${app.api.gateway.url}/api/auth

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.example.frontend: DEBUG
    org.springframework.cloud: INFO