spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5433/notification_bd
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  mail:
    properties:
      mail:
        debug: false

server:
  port: 8085
  servlet:
    context-path: /notification-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      notificationService:
        baseConfig: default
        registerHealthIndicator: true

  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
    instances:
      notificationService:
        baseConfig: default
        
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

notification:
  deadline:
    check-interval: 60000  # 1 минута для тестирования
    reminder-hours: 24     # Напоминать за 24 часа до дедлайна

logging:
  level:
    org.example.notification: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/notification-service.log