spring:
  application:
    name: search-service
  datasource:
    url: jdbc:postgresql://localhost:5432/search_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 10s

server:
  port: 8085

# Специфичные настройки Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      searchService:
        baseConfig: default
        registerHealthIndicator: true
  timelimiter:
    instances:
      searchService:
        baseConfig: default

# Специфичные настройки логирования
logging:
  level:
    com.example.searchservice: DEBUG
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch: WARN
  file:
    name: logs/search-service.log
    max-size: 10MB
    max-history: 14

# Настройки SpringDoc
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.example.searchservice.controller
  paths-to-match: /api/**

info:
  app:
    name: Search Service
    description: Microservice for search functionality
    version: 1.0.0