spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://localhost:5433/task_bd
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,circuitbreakers,prometheus
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
      show-components: always
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      taskService:
        baseConfig: default
        registerHealthIndicator: true
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
    instances:
      taskService:
        baseConfig: default

logging:
  level:
    org.hibernate.type: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.cloud.circuitbreaker: DEBUG
    io.github.resilience4j: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  file:
    max-size: 10MB
    max-history: 7