spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://localhost:5433/task_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

# Специфичные настройки Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      taskService:
        baseConfig: default
        registerHealthIndicator: true
  timelimiter:
    instances:
      taskService:
        baseConfig: default

# Специфичные настройки логирования
logging:
  level:
    com.example.taskservice: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
  file:
    name: logs/task-service.log
    max-size: 10MB
    max-history: 14

# Настройки SpringDoc
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.example.taskservice.controller
  paths-to-match: /api/**

info:
  app:
    name: Task Service
    description: Microservice for task management
    version: 1.0.0