spring:
  application:
    name: task-service

server:
  port: 8081

datasource:
  url: jdbc:postgresql://localhost:5433/task_bd
  username: postgres
  password: 123
  driver-class-name: org.postgresql.Driver

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans
  endpoint:
    health:
      show-details: always
      show-components: always

logging:
  level:
    org.example.task: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.web: DEBUG