spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: false
  cloud:
    discovery:
      enabled: true

server:
  port: 8087
  servlet:
    context-path: /user-service

# Специфичные настройки Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      userService:
        baseConfig: default
        registerHealthIndicator: true
  timelimiter:
    instances:
      userService:
        baseConfig: default
  retry:
    instances:
      userService:
        baseConfig: default

# Специфичные настройки логирования
logging:
  level:
    com.example.userservice: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  file:
    name: logs/user-service.log
    max-size: 10MB
    max-history: 30

# Настройки SpringDoc
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.example.userservice.controller
  paths-to-match: /user-service/**

info:
  app:
    name: User Service
    description: Microservice for user management and authentication
    version: 1.0.0